=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.example.com"
    xmlns="https://www.example.com"
    elementFormDefault="qualified"
>

    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>

              <xs:element name="film" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="genre" type="xs:string"/>
                        <xs:element name="director" type="xs:string"/>
                        <xs:element name="duration" type="xs:duration"/>
                        <xs:element name="contentRating" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies
	xmlns="https://www.example.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.example.com cinema.xsd"
>
	<film>
		<title>Inception</title>
		<genre>Sci-Fi</genre>
		<director>Christopher Nolan</director>
		<duration>PT2H28M</duration>
		<contentRating>PG-13</contentRating>
	</film>
	<film>
		<title>Spirited Away</title>
		<genre>Animation</genre>
		<director>Hayao Miyazaki</director>
		<duration>PT2H5M</duration>
		<contentRating>PG</contentRating>
	</film>
</movies>
