=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/retail.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.example.com"
  xmlns="https://www.example.com"
  elementFormDefault="qualified"
>

    <xs:element name="retail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="store">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="brand" type="xs:string"/>
                            <xs:element name="product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="price">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="currency" use="required">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="PHP"></xs:enumeration>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="stockCount"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/retail.xml
<?xml version="1.0" encoding="UTF-8"?>
<retail
	xmlns="https://www.example.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.example.com retail.xsd"
>
	<store>
		<type>Electronics</type>
		<brand>TechWorld</brand>
		<product>
			<price currency="PHP">2999.99</price>
			<stockCount>15</stockCount>
		</product>
		<product>
			<price currency="PHP">15999.50</price>
			<stockCount>7</stockCount>
		</product>
	</store>
</retail>
