=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/university.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.example.com"
  xmlns="https://www.example.com"
  elementFormDefault="qualified"
>

    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="departments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name='department' maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="college" type="xs:string"/>
                                        <xs:element name="studentCount" type="xs:int"/>
                                        <xs:element name="students">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="studentId" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== carlo-baron/prin-143-midterm-activity-03--Cortez---Rodriguez---Baron-/university.xml
<?xml version="1.0" encoding="UTF-8"?>
<university
	xmlns="https://www.example.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.example.com university.xsd"
>
	<departments>
		<department>
			<college>College of Engineering</college>
			<studentCount>2</studentCount>
			<students>
				<name>Ana Cruz</name>
				<studentId>ENG2024001</studentId>
			</students>
			<students>
				<name>Mark Reyes</name>
				<studentId>ENG2024002</studentId>
			</students>
		</department>
		<department>
			<college>College of Computer Science</college>
			<studentCount>1</studentCount>
			<students>
				<name>John Dela Cruz</name>
				<studentId>CS2024001</studentId>
			</students>
		</department>
	</departments>
</university>
